name: Continuous Integration
on:
  push:
    branches:
      - "**"

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Prettier Format Check
        run: npm run format-check
      - name: ESLint Check
        run: npm run lint
      - name: Test
        run: npm test -- --reporter verbose
      - name: Build
        run: npm run build
